name: 'Install and verify dependencies for the Benchmarkoor GitHub Action'
description: 'Install required dependencies for Benchmarkoor (zip/unzip, GitHub CLI, yq)'
author: 'ethpandaops'

runs:
  using: 'composite'
  steps:
    - name: Install zip/unzip if not present
      shell: bash
      run: |
        # Check if zip and unzip are available
        ZIP_MISSING=false
        UNZIP_MISSING=false

        if ! command -v zip &> /dev/null; then
          echo "zip command not found"
          ZIP_MISSING=true
        fi

        if ! command -v unzip &> /dev/null; then
          echo "unzip command not found"
          UNZIP_MISSING=true
        fi

        if [ "$ZIP_MISSING" = true ] || [ "$UNZIP_MISSING" = true ]; then
          echo "Installing zip/unzip utilities..."

          # Detect OS
          if [[ "$OSTYPE" == "linux-gnu"* ]]; then
            # Linux - assume Ubuntu/Debian
            sudo apt update
            sudo apt install -y zip unzip
          elif [[ "$OSTYPE" == "darwin"* ]]; then
            # macOS - zip/unzip should be pre-installed, but check with brew if needed
            if command -v brew &> /dev/null; then
              if [ "$ZIP_MISSING" = true ]; then
                brew install zip
              fi
              # unzip is typically pre-installed on macOS
            else
              echo "zip/unzip utilities appear to be missing and Homebrew not found"
              echo "Please install zip/unzip manually"
              exit 1
            fi
          else
            echo "Unsupported OS. Please install zip/unzip manually"
            exit 1
          fi

          echo "zip/unzip utilities installed successfully"
        else
          echo "zip and unzip are already available"
        fi

    - name: Install GitHub CLI if not present
      shell: bash
      run: |
        if ! command -v gh &> /dev/null; then
          echo "GitHub CLI not found, installing..."

          # Detect OS
          if [[ "$OSTYPE" == "linux-gnu"* ]]; then
            # Linux - assume Ubuntu/Debian
            (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
              && mkdir -p -m 755 /etc/apt/keyrings \
              && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
              && cat $out | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
              && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
              && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install -y gh
          elif [[ "$OSTYPE" == "darwin"* ]]; then
            # macOS
            if command -v brew &> /dev/null; then
              brew install gh
            else
              echo "Homebrew not found. Please install GitHub CLI manually: https://cli.github.com/"
              exit 1
            fi
          else
            echo "Unsupported OS. Please install GitHub CLI manually: https://cli.github.com/"
            exit 1
          fi

          echo "GitHub CLI installed successfully"
        else
          echo "GitHub CLI already installed"
          gh --version
        fi

    - name: Setup Podman and CRIU
      shell: bash
      run: |
        # Ensure podman is available (pre-installed on ubuntu-latest)
        if command -v podman &> /dev/null; then
          echo "Podman already installed"
          podman --version
        else
          echo "Installing podman..."
          sudo apt-get update
          sudo apt-get install -y podman
        fi

        # Install CRIU for checkpoint-restore support.
        # On Ubuntu 24.04 CRIU is not in default repos; use the official PPA.
        # On Debian, CRIU is available in the default repos.
        if [[ "$OSTYPE" == "linux-gnu"* ]]; then
          if [ -f /etc/os-release ]; then
            . /etc/os-release
          fi
          if [ "${ID:-}" = "ubuntu" ]; then
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:criu/ppa
            sudo apt-get update
          fi
          sudo apt-get install -y criu
          echo "CRIU installed: $(criu --version 2>&1 | head -1)"
        else
          echo "CRIU installation not supported on this OS, skipping"
        fi

        # Replace crun with a release binary that has +CRIU support.
        # Ubuntu 24.04's crun 1.14.1 is compiled without +CRIU;
        # checkpoint/restore requires a crun linked against libcriu.
        CRUN_VERSION="1.26"
        CRUN_SHA256="8b37b0f8bfa170a9c338fa869902a33991101264ce0764e776a997a8d787dc83"
        echo "Installing crun ${CRUN_VERSION} with CRIU support..."
        sudo curl -fsSL -o /usr/bin/crun \
          "https://github.com/containers/crun/releases/download/${CRUN_VERSION}/crun-${CRUN_VERSION}-linux-amd64"
        echo "${CRUN_SHA256}  /usr/bin/crun" | sha256sum --check --strict
        sudo chmod +x /usr/bin/crun
        echo "crun installed: $(crun --version | head -2)"

        # Start the rootful podman socket
        sudo systemctl start podman.socket
        echo "Podman socket started"

        # Verify socket is accessible. systemd socket activation creates
        # the socket file lazily on first connection, so trigger it with
        # a podman command instead of checking the file directly.
        if sudo podman info --format '{{.Host.RemoteSocket.Exists}}' 2>/dev/null | grep -q true; then
          echo "Podman socket is available at /run/podman/podman.sock"
        else
          echo "WARNING: Podman socket not available"
        fi

        # Print runtime info for debugging
        echo "--- Podman info ---"
        sudo podman info

    - name: Install yq if not present
      shell: bash
      run: |
        if ! command -v yq &> /dev/null; then
          echo "yq not found, installing..."
          if [[ "$OSTYPE" == "linux-gnu"* ]]; then
            YQ_VERSION="v4.44.6"
            sudo wget -qO /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64"
            sudo chmod +x /usr/local/bin/yq
          elif [[ "$OSTYPE" == "darwin"* ]]; then
            if command -v brew &> /dev/null; then
              brew install yq
            else
              echo "Homebrew not found. Please install yq manually: https://github.com/mikefarah/yq"
              exit 1
            fi
          else
            echo "Unsupported OS. Please install yq manually: https://github.com/mikefarah/yq"
            exit 1
          fi
          echo "yq installed successfully"
        else
          echo "yq already installed"
          yq --version
        fi
